#!/bin/bash -e

PLATFORMS="linux/amd64,linux/arm64"
EXTRA_BUILDX_ARGS=$@
CACHE_LOCATION="/tmp/docker-cache"

if [[ "${EXTRA_BUILDX_ARGS}" == *"--push"* || "${EXTRA_BUILDX_ARGS}" == *"--load"* ]]; then
    CACHE="--cache-from=type=local,src=${CACHE_LOCATION}"
else
    CACHE="--cache-to=type=local,dest=${CACHE_LOCATION}"
fi

docker buildx build \
    $CACHE \
    --platform "${PLATFORMS}" \
    --progress=plain \
    --build-arg kafka_version=$KAFKA_VERSION \
    --build-arg scala_version=$SCALA_VERSION \
    --build-arg vcs_ref=$GITHUB_SHA \
    --build-arg build_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
    -t krelms/kafka \
    $EXTRA_BUILDX_ARGS \
    .